name: Provision Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to perform.'
        required: true
        default: 'provision'
        type: choice
        options:
        - provision
        - destroy
      resource-group-name:
        description: 'The name of the Azure Resource Group to provision to or destroy.'
        required: true

jobs:
  provision-vms:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the latest main branch
      - name: Checkout latest main
        uses: actions/checkout@v4

      # Step 2: Verify provisioning script
      - name: Verify provisioning script
        run: |
          Get-Content ./Invoke-AzureProvisioning.ps1
        shell: pwsh

      # Step 3: Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Create SSH key file from secret
      - name: Create SSH key file from secret
        run: |
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > id_rsa.pub
        shell: bash

      # Step 5: Run PowerShell provisioning script
      - name: Run PowerShell provisioning script
        if: ${{ github.event.inputs.action == 'provision' }}
        run: |
          ./Invoke-AzureProvisioning.ps1 `
            -ResourceGroupName ${{ github.event.inputs.resource-group-name }} `
            -VMLocation 'eastus' `
            -AdminUsername 'azureuser' `
            -AdminSshKeyFile "id_rsa.pub" `
            -VMNames 'pihole-vm','dynatrace-vm'
        shell: pwsh

      # Step 6: Run PowerShell destruction script
      - name: Run PowerShell destruction script
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          ./Destroy-AzureResources.ps1 `
            -ResourceGroupName ${{ github.event.inputs.resource-group-name }} `
            -Force
        shell: pwsh
