name: Provision Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to perform.'
        required: true
        type: choice
        options:
          - provision
      resource-group-name:
        description: 'The name of the Azure Resource Group to provision to or destroy.'
        required: true

jobs:
  provision-vms:
    runs-on: ubuntu-latest
    env:
      AZURE_LOCATION: 'eastus'
      VM_USERNAME: 'nicolasnk'

    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Verify provisioning script
        shell: pwsh
        run: |
          Write-Host "Top lines of Invoke-AzureProvisioning.ps1:"
          Get-Content ./Invoke-AzureProvisioning.ps1 | Select-Object -First 10

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create SSH key file from secret
        run: |
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > id_rsa.pub
        shell: bash

      - name: Run PowerShell provisioning script
        if: ${{ github.event.inputs.action == 'provision' }}
        shell: pwsh
        run: |
          ./Invoke-AzureProvisioning.ps1 `
            -resourceGroupName ${{ github.event.inputs.resource-group-name }} `
            -location $env:AZURE_LOCATION `
            -username $env:VM_USERNAME `
            -sshKeyContent '${{ secrets.SSH_PUBLIC_KEY }}' `
            -vmPiholeName pihole-vm `
            -vmDynatraceName dynatrace-vm
