name: Provision Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to perform.'
        required: true
        default: 'provision'
        type: choice
        options:
        - provision
        - destroy
      resource-group-name:
        description: 'The name of the Azure Resource Group to provision to or destroy.'
        required: true

jobs:
  provision-vms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4

      - name: Verify provisioning script
        run: |
          Get-Content ./Invoke-AzureProvisioning.ps1
        shell: pwsh

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create SSH key file from secret
        run: |
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > id_rsa.pub
        shell: bash

      - name: Run PowerShell provisioning script
        if: ${{ github.event.inputs.action == 'provision' }}
        run: |
          ./Invoke-AzureProvisioning.ps1 `
            -ResourceGroupName ${{ github.event.inputs.resource-group-name }} `
            -VMLocation 'eastus' `
            -AdminUsername 'admin' `
            -AdminSshKeyFile "id_rsa.pub" `
            -VMNames 'pihole-vm','dynatrace-vm'
        shell: pwsh

      - name: Run PowerShell destruction script
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          ./Destroy-AzureResources.ps1 `
            -ResourceGroupName ${{ github.event.inputs.resource-group-name }}
        shell: pwsh
