name: Provision Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to perform.'
        required: true
        type: choice
        options:
          - provision
          - destroy

env:
  AZURE_RESOURCE_GROUP: 'pihole-dynatrace-rg'
  AZURE_LOCATION: 'eastus'
  VM_USERNAME: 'nicolasnk'
  
permissions:
  id-token: write
  contents: read

jobs:
  provision-vms:
    if: github.event.inputs.action == 'provision'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run PowerShell provisioning script
        shell: pwsh
        run: |
          ./Invoke-AzureProvisioning.ps1 `
            -ResourceGroupName $env:AZURE_RESOURCE_GROUP `
            -VMLocation $env:AZURE_LOCATION `
            -AdminUsername $env:VM_USERNAME `
            -AdminSshKeyFile "id_rsa.pub" `
            -VMNames 'pihole-vm','dynatrace-vm'
  
  destroy-vms:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Run PowerShell destruction script
        shell: pwsh
        run: |
          ./Destroy-AzureResources.ps1 `
            -ResourceGroupName "$ENV:AZURE_RESOURCE_GROUP"
